import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {mkdtemp,rm,readFile,writeFile,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AgentManager,safeEnv,command} from '../core.mjs';

async function fixture(t,options={}){const dir=await mkdtemp(join(tmpdir(),'session-agents-test-'));const calls=[];const runner=(binary,args,opts)=>{const c=new EventEmitter();Object.assign(c,{pid:999999,stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),kill(){c.emit('close',null);}});calls.push({binary,args,opts,c});return c;};const manager=new AgentManager({stateDir:join(dir,'state'),runner,authCheck:async provider=>({provider,available:true,authenticated:true}),kill:c=>c.kill(),...options});await manager.ready;t.after(async()=>{await manager.shutdown();await rm(dir,{recursive:true,force:true});});return {manager,calls,dir};}
async function waitDone(manager,id){for(let i=0;i<100;i++){if(manager.status(id).status!=='running'){await new Promise(r=>setTimeout(r,10));return;}await new Promise(r=>setTimeout(r,10));}throw Error('Test completion timeout');}
test('lifecycle, bounded output, private persistence and argv input',async t=>{const {manager,calls,dir}=await fixture(t,{maxOutput:10});const job=await manager.start({provider:'codex',prompt:'private prompt',cwd:dir});assert.equal(job.status,'running');assert.equal(calls[0].opts.shell,false);assert.equal(calls[0].opts.detached,true);assert.equal(calls[0].args.includes('private prompt'),false);calls[0].c.stdout.write('123456789012345\n');calls[0].c.stdout.write(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'done'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n');calls[0].c.stderr.write('secret');calls[0].c.emit('close',0);await waitDone(manager,job.id);assert.equal(manager.result(job.id).output,'1234567890');assert.equal(manager.result(job.id).truncated,true);assert.equal(manager.status(job.id).status,'completed');const file=join(dir,'state',job.id+'.json');assert.equal((await stat(file)).mode&0o777,0o600);assert.equal((await readFile(file,'utf8')).includes('private prompt'),false);});
test('concurrency and cancel preserve terminal reason',async t=>{const {manager,dir}=await fixture(t);const input={provider:'codex',prompt:'task',cwd:dir};const [a,b,c]=await Promise.allSettled([manager.start(input),manager.start(input),manager.start(input)]);assert.equal(a.status,'fulfilled');assert.equal(b.status,'fulfilled');assert.equal(c.status,'rejected');assert.equal((await manager.cancel(a.value.id)).status,'cancelled');await manager.start(input);});
test('reject invalid cwd and missing provider login before launch',async t=>{const {manager,calls,dir}=await fixture(t);await assert.rejects(manager.start({provider:'codex',prompt:'task',cwd:join(dir,'missing')}),/directory/);manager.authCheck=async()=>({available:true,authenticated:false});await assert.rejects(manager.start({provider:'claude',prompt:'task',cwd:dir}),/login/);assert.equal(calls.length,0);});
test('timeout kills agent and does not become failed on close',async t=>{const {manager,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir,timeoutSeconds:1});await new Promise(r=>setTimeout(r,1100));assert.equal(manager.status(job.id).status,'timed-out');assert.equal(manager.running.size,0);});
test('restart marks orphan running jobs interrupted',async t=>{const {manager,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});const persisted=manager.result(job.id);await writeFile(join(dir,'state',job.id+'.json'),JSON.stringify({...persisted,ownerPid:999999}));const restored=new AgentManager({stateDir:join(dir,'state')});await restored.ready;assert.equal(restored.status(job.id).status,'interrupted');});
test('environment excludes API credentials and claude commands constrain tools',()=>{const env=safeEnv({HOME:'/tmp',PATH:'/bin',OPENAI_API_KEY:'secret',ANTHROPIC_API_KEY:'secret',CLAUDE_CODE_OAUTH_TOKEN:'secret'});assert.deepEqual(env,{HOME:'/tmp',PATH:'/bin'});for(const mode of ['read-only','workspace-write']){const [,args]=command('claude',{mode});assert.equal(args.includes('--bare'),false);assert.equal(args.includes('--strict-mcp-config'),true);assert.equal(args.join(' ').includes('Bash'),false);}assert.equal(command('claude',{mode:'read-only'})[1].includes('Read,Glob,Grep,Edit,Write'),false);});

test('exit zero without completion or with provider error is failed',async t=>{const {manager,calls,dir}=await fixture(t);for(const [provider,event] of [['codex',{type:'error',message:'private diagnostic'}],['claude',{type:'result',subtype:'error_during_execution',is_error:true}],['codex',{type:'turn.started'}]]){const job=await manager.start({provider,prompt:'task',cwd:dir});const child=calls.at(-1).c;child.stdout.write(JSON.stringify(event)+'\n');child.emit('close',0);await waitDone(manager,job.id);assert.equal(manager.status(job.id).status,'failed');}});
test('provider crash reports exit code and category without persisting stderr',async t=>{const {manager,calls,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});const child=calls.at(-1).c;child.stderr.write("thread 'worker' pani");child.stderr.write('cked at private/path: private-secret-value');child.emit('close',101);await waitDone(manager,job.id);const result=manager.result(job.id);assert.equal(result.status,'failed');assert.equal(result.exitCode,101);assert.equal(result.failureKind,'runtime-panic');assert.match(result.reason,/code 101.*runtime-panic/);const persisted=await readFile(join(dir,'state',job.id+'.json'),'utf8');assert.equal(persisted.includes('private/path'),false);assert.equal(persisted.includes('private-secret-value'),false);});
test('Claude success collects session and result after output truncation',async t=>{const {manager,calls,dir}=await fixture(t,{maxOutput:10});const job=await manager.start({provider:'claude',prompt:'task',cwd:dir});const child=calls[0].c;child.stdout.write('ignored preamble\n');child.stdout.write(JSON.stringify({type:'result',subtype:'success',is_error:false,session_id:'session-1',result:'hello'})+'\n');child.emit('close',0);await waitDone(manager,job.id);assert.equal(manager.result(job.id).status,'completed');assert.equal(manager.result(job.id).sessionId,'session-1');assert.equal(manager.result(job.id).finalResult,'hello');assert.equal(manager.result(job.id).truncated,true);});
test('API-key login is rejected, existing subscription login accepted',async t=>{const {manager,calls}=await fixture(t);for(const [provider,text,expected] of [['codex','Logged in using an API key',false],['codex','Logged in using ChatGPT',true],['claude',JSON.stringify({loggedIn:true,authMethod:'api_key'}),false],['claude',JSON.stringify({loggedIn:true,authMethod:'claude.ai'}),true]]){const promise=manager.checkAuth(provider);calls.at(-1).c.stdout.write(text);calls.at(-1).c.emit('close',0);assert.equal((await promise).authenticated,expected);}});
test('persistence failure on completion becomes visible without unhandled rejection',async t=>{const {manager,calls,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});manager.persist=async()=>{throw Error('disk failure');};calls[0].c.stdout.write(JSON.stringify({type:'turn.completed'})+'\n');calls[0].c.emit('close',0);await waitDone(manager,job.id);assert.equal(manager.status(job.id).persistenceError,true);});

test('another manager preserves live owners and refreshes completed results',async t=>{const {manager,calls,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});assert.equal(manager.result(job.id).ownerPid,process.pid);const observer=new AgentManager({stateDir:join(dir,'state')});await observer.ready;assert.equal(observer.status(job.id).status,'running');calls[0].c.stdout.write(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'cross process result'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n');calls[0].c.emit('close',0);await waitDone(manager,job.id);assert.equal((await observer.readStatus(job.id)).status,'completed');assert.equal((await observer.readResult(job.id)).finalResult,'cross process result');assert.equal((await observer.list())[0].status,'completed');});
test('legacy running records without an owner are interrupted',async t=>{const {manager,dir}=await fixture(t);const id='legacy-running-job';await writeFile(join(dir,'state',id+'.json'),JSON.stringify({id,status:'running',output:''}));assert.equal((await manager.readStatus(id)).status,'interrupted');});

test('refresh cannot overwrite an owned completion while persistence is pending',async t=>{const {manager,calls,dir}=await fixture(t);const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});const original=manager.persist.bind(manager);let release;const gate=new Promise(r=>release=r);manager.persist=async j=>{await gate;await original(j);};calls[0].c.stdout.write(JSON.stringify({type:'turn.completed'})+'\n');calls[0].c.emit('close',0);assert.equal((await manager.readStatus(job.id)).status,'completed');assert.equal((await manager.list())[0].status,'completed');release();await new Promise(r=>setTimeout(r,10));});

test('real cancellation waits for SIGTERM-ignoring writer and descendants before freeing slot',async t=>{
 const {spawn}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'session-real-stop-'));const marker=join(dir,'writes.txt');
 const writer=`const fs=require('node:fs');process.on('SIGTERM',()=>{});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'x'),15);`;
 const script=`const fs=require('node:fs');const {spawn}=require('node:child_process');process.on('SIGTERM',()=>{});spawn(process.execPath,['-e',${JSON.stringify(writer)}],{stdio:['ignore','inherit','inherit']});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'p'),15);`;
 const manager=new AgentManager({stateDir:join(dir,'state'),maxConcurrent:1,authCheck:async()=>({available:true,authenticated:true}),runner:(_binary,_args,opts)=>spawn(process.execPath,['-e',script],opts)});t.after(async()=>{await manager.shutdown();await rm(dir,{recursive:true,force:true});});
 const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});for(let i=0;i<100;i++){try{if((await readFile(marker,'utf8')).includes('x'))break;}catch{}await new Promise(r=>setTimeout(r,10));}assert.equal((await readFile(marker,'utf8')).includes('x'),true);
 let cancelled=false;const stopping=manager.cancel(job.id).then(result=>{cancelled=true;return result;});await new Promise(r=>setTimeout(r,50));assert.equal(cancelled,false);assert.equal(manager.running.size,1);assert.equal(manager.status(job.id).status,'running');assert.equal(manager.status(job.id).stopRequested,'cancelled');await assert.rejects(manager.start({provider:'codex',prompt:'second writer',cwd:dir}),/Concurrent/);
 assert.equal((await stopping).status,'cancelled');assert.equal(manager.running.size,0);const bytes=(await stat(marker)).size;await new Promise(r=>setTimeout(r,100));assert.equal((await stat(marker)).size,bytes);
});
test('real timeout remains active until ignoring child closes',async t=>{
 const {spawn}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'session-real-timeout-'));const marker=join(dir,'writes.txt');const script=`const fs=require('node:fs');process.on('SIGTERM',()=>{});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'x'),15);`;
 const manager=new AgentManager({stateDir:join(dir,'state'),authCheck:async()=>({available:true,authenticated:true}),runner:(_binary,_args,opts)=>spawn(process.execPath,['-e',script],opts)});t.after(async()=>{await manager.shutdown();await rm(dir,{recursive:true,force:true});});const job=await manager.start({provider:'codex',prompt:'task',cwd:dir,timeoutSeconds:1});await new Promise(r=>setTimeout(r,1100));assert.equal(manager.status(job.id).status,'running');assert.equal(manager.status(job.id).stopRequested,'timed-out');assert.equal(manager.running.size,1);await new Promise(r=>setTimeout(r,1100));assert.equal(manager.status(job.id).status,'timed-out');assert.equal(manager.running.size,0);const bytes=(await stat(marker)).size;await new Promise(r=>setTimeout(r,100));assert.equal((await stat(marker)).size,bytes);
});

test('supervisor kills detached provider and writer descendants when owner is SIGKILLed',async t=>{
 const {spawn}=await import('node:child_process');const {chmod}=await import('node:fs/promises');const {fileURLToPath,pathToFileURL}=await import('node:url');const dir=await mkdtemp(join(tmpdir(),'session-owner-death-'));const marker=join(dir,'writes.txt'),stateDir=join(dir,'state'),binary=join(dir,'codex');
 const writer=`const fs=require('node:fs');process.on('SIGTERM',()=>{});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'x'),15);`;
 await writeFile(binary,`#!/usr/bin/env node\nconst fs=require('node:fs');const {spawn}=require('node:child_process');process.on('SIGTERM',()=>{});spawn(process.execPath,['-e',${JSON.stringify(writer)}],{stdio:['ignore','inherit','inherit']});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'p'),15);`);await chmod(binary,0o700);
 const moduleURL=pathToFileURL(fileURLToPath(new URL('../core.mjs',import.meta.url))).href;const script=`import {AgentManager} from ${JSON.stringify(moduleURL)};process.env.PATH=${JSON.stringify(dir)}+':'+process.env.PATH;const m=new AgentManager({stateDir:${JSON.stringify(stateDir)},authCheck:async()=>({available:true,authenticated:true})});const job=await m.start({provider:'codex',prompt:'task',cwd:${JSON.stringify(dir)}});console.log(JSON.stringify(job));setInterval(()=>{},1000);`;
 const parent=spawn(process.execPath,['--input-type=module','-e',script],{stdio:['ignore','pipe','pipe']});let job;try{let stdout='';job=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('owner startup timeout')),5000);parent.stdout.on('data',b=>{stdout+=b;const line=stdout.split('\n').find(l=>l.startsWith('{'));if(line){clearTimeout(timer);resolve(JSON.parse(line));}});parent.on('error',reject);});assert.ok(job.supervisorPid);for(let i=0;i<200;i++){try{if((await readFile(marker,'utf8')).includes('x'))break;}catch{}await new Promise(r=>setTimeout(r,10));}assert.equal((await readFile(marker,'utf8')).includes('x'),true);parent.kill('SIGKILL');await new Promise(r=>parent.once('close',r));const restored=new AgentManager({stateDir});await restored.ready;assert.equal((await restored.readStatus(job.id)).status,'interrupted');const bytes=(await stat(marker)).size;await new Promise(r=>setTimeout(r,300));assert.equal((await stat(marker)).size,bytes);}finally{try{parent.kill('SIGKILL');if(job)process.kill(-job.supervisorPid,'SIGKILL');}catch{}await rm(dir,{recursive:true,force:true});}
});

test('native successful provider completion kills leftover background writer before releasing slot',async t=>{
 const {chmod}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'session-completed-background-'));const marker=join(dir,'writes.txt'),binary=join(dir,'codex');const writer=`const fs=require('node:fs');process.on('SIGTERM',()=>{});setInterval(()=>fs.appendFileSync(${JSON.stringify(marker)},'x'),10);`;
 const success=JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'done'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n';
 await writeFile(binary,`#!/usr/bin/env node\nconst {spawn}=require('node:child_process');spawn(process.execPath,['-e',${JSON.stringify(writer)}],{stdio:'ignore',detached:false});setTimeout(()=>{process.stdout.write(${JSON.stringify(success)},()=>process.exit(0));},150);`);await chmod(binary,0o700);
 const previousPath=process.env.PATH;process.env.PATH=dir+':'+previousPath;const manager=new AgentManager({stateDir:join(dir,'state'),authCheck:async()=>({available:true,authenticated:true})});t.after(async()=>{process.env.PATH=previousPath;await manager.shutdown();await rm(dir,{recursive:true,force:true});});const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});await waitDone(manager,job.id);assert.equal(manager.status(job.id).status,'completed');assert.equal(manager.running.size,0);assert.equal(manager.result(job.id).finalResult,'done');const bytes=(await stat(marker)).size;assert.ok(bytes>0);await new Promise(r=>setTimeout(r,200));assert.equal((await stat(marker)).size,bytes);
});

test('supervised blocking provider output survives a multi-megabyte burst and preserves completion',async t=>{
 const {chmod}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'session-large-stdout-')),binary=join(dir,'codex');
 const success=JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'large-output-completed'}})+'\n'+JSON.stringify({type:'turn.completed'})+'\n';
 await writeFile(binary,`#!/usr/bin/env node\nconst fs=require('node:fs');const data=Buffer.from('x'.repeat(4*1024*1024)+'\\n'+${JSON.stringify(success)});let offset=0;try{while(offset<data.length)offset+=fs.writeSync(1,data,offset,data.length-offset);}catch(e){fs.writeSync(2,String(e));process.exitCode=101;}`);await chmod(binary,0o700);
 const previousPath=process.env.PATH;process.env.PATH=dir+':'+previousPath;const manager=new AgentManager({stateDir:join(dir,'state'),authCheck:async()=>({available:true,authenticated:true})});t.after(async()=>{process.env.PATH=previousPath;await manager.shutdown();await rm(dir,{recursive:true,force:true});});
 const job=await manager.start({provider:'codex',prompt:'task',cwd:dir});await waitDone(manager,job.id);const result=manager.result(job.id);assert.equal(result.status,'completed');assert.equal(result.exitCode,0);assert.equal(result.finalResult,'large-output-completed');assert.equal(result.truncated,true);
});
