import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createGateway} from '../gateway.mjs';
const token='gateway-oauth-test-admin-private-123456789';
async function fixture(t){const gateway=createGateway({token,publicUrl:'https://bongee.example'});await gateway.ready;const server=gateway.app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));t.after(()=>new Promise(r=>server.close(r)));const url='http://127.0.0.1:'+server.address().port;const request=(path,{method='GET',bearer,body,cookie}={})=>fetch(url+path,{method,redirect:'manual',headers:{...(bearer?{Authorization:'Bearer '+bearer}:{}),...(cookie?{Cookie:cookie}:{}),'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {...gateway,request};}
test('URL landing is public; MCP requires discoverable OAuth and private runner credentials remain purpose bound',async t=>{const g=await fixture(t);assert.equal((await g.request('/mcp')).status,200);const denied=await g.request('/mcp',{method:'POST',body:{}});assert.equal(denied.status,401);assert.match(denied.headers.get('www-authenticate'),/resource_metadata=.*oauth-protected-resource\/mcp/);const user=randomUUID(),cred=await g.store.provisionRunner(user);assert.equal((await g.request('/runner/status',{bearer:cred.runnerToken})).status,200);assert.equal((await g.request('/mcp',{method:'POST',bearer:cred.runnerToken,body:{}})).status,401);});
test('independent tenants cannot claim, read or cancel owner jobs and OAuth cannot use runner endpoints',async t=>{const g=await fixture(t),id=randomUUID();g.oauth.authenticate=async req=>req.headers.authorization==='Bearer test-oauth'?{id,kind:'oauth'}:null;await g.request('/runner/heartbeat',{method:'POST',bearer:token,body:{providers:[{provider:'codex',available:true,authenticated:true}]}});const job=await g.call('bongee_remote_agent_start',{provider:'codex',prompt:'owner-secret',cwd:'/tmp'});assert.deepEqual(await g.call('bongee_remote_agent_list',{},id),[]);await assert.rejects(g.call('bongee_remote_agent_result',{id:job.id},id),/Unknown/);assert.equal((await g.request('/runner/claim',{method:'POST',bearer:'test-oauth',body:{}})).status,401);const response=await g.request('/connection/runner',{method:'POST',bearer:'test-oauth',body:{principal:'owner'}});assert.equal(response.status,200);const credential=await response.json();assert.equal(credential.principal,id);assert.equal((await g.request('/owner/bootstrap',{method:'POST',bearer:'test-oauth',body:{}})).status,403);assert.equal((await (await g.request('/runner/claim',{method:'POST',bearer:credential.token,body:{}})).json()).job,null);});
test('setup download requires browser bound confirmation and bootstrap is privileged and one use',async t=>{const g=await fixture(t);assert.equal((await g.request('/setup',{method:'POST',body:{nonce:'forged'}})).status,403);const response=await g.request('/owner/bootstrap',{method:'POST',bearer:token,body:{}});assert.equal(response.status,200);const codeUrl=(await response.json()).url;const path=new URL(codeUrl).pathname+new URL(codeUrl).search;const boot=await g.request(path);assert.equal(boot.status,302);assert.ok(boot.headers.get('set-cookie'));assert.equal((await g.request(path)).status,400);});
test('browser setup creates a private downloadable executor without sharing owner runner',async t=>{const g=await fixture(t);const response=await g.request('/setup');assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0],html=await response.text(),nonce=html.match(/name="nonce" value="([^"]+)"/)[1];const download=await g.request('/setup',{method:'POST',cookie,body:{nonce}});assert.equal(download.status,200);assert.equal(download.headers.get('cache-control'),'no-store');assert.equal(download.headers.get('content-type'),'application/zip');const zip=Buffer.from(await download.arrayBuffer());assert.equal(zip.readUInt32LE(0),0x04034b50);assert.ok(zip.includes(Buffer.from('connection.json')));assert.equal((await g.request('/setup',{method:'POST',cookie,body:{nonce}})).status,403);});
test('public setup visits do not allocate tenant capacity',async t=>{const g=await fixture(t);for(let i=0;i<70;i++)assert.equal((await g.request('/setup')).status,200);assert.equal(g.store.tenants.size,1);const credential=await g.store.provisionRunner(randomUUID());assert.ok(credential.runnerToken);});
