import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,rm,writeFile}from 'node:fs/promises';import {tmpdir}from 'node:os';import{join}from 'node:path';import{PipelineManager}from '../pipeline.mjs';import{workspaceFingerprint}from '../verification.mjs';import{parseRoleResult}from '../pipeline-contracts.mjs';
const output={planner:{goals:['complete'],requirements:[{id:'R1',description:'works',verification:'test'}]},researcher:{findings:['source'],constraints:[]},architect:{implementationPlan:['implement'],files:[]},designer:{hasUI:false,specification:[],noUIReason:'CLI'},developer:{summary:'implemented',changedFiles:[]},tester:{verdict:'pass',acceptance:[{id:'R1',status:'pass',evidence:'test passed'}],findings:[]},reviewer:{verdict:'pass',findings:[]}};
async function fixture({results={},delay=0,checks}={}){const dir=await mkdtemp(join(tmpdir(),'pipeline-'));const cwd=join(dir,'workspace');await mkdir(cwd);let n=0;const jobs=new Map(),calls=[];const manager={stateDir:dir,ready:Promise.resolve(),async start(input){calls.push(input);const id=String(++n),value=results[input.role]??output[input.role];jobs.set(id,{id,status:'running',finalResult:JSON.stringify(value)});setTimeout(()=>{if(jobs.get(id).status==='running')jobs.get(id).status='completed';},delay);return{id,status:'running'};},async readResult(id){return jobs.get(id);},async cancel(id){jobs.get(id).status='cancelled';}};let count=0;const verifier={async run(){count++;const fingerprint=await workspaceFingerprint(cwd);return {fingerprintBefore:fingerprint,fingerprintAfter:fingerprint,...(checks?checks(count):{passed:true,checks:[{id:'test',status:'passed'}],workspaceChanged:false})};}};const pipeline=new PipelineManager({manager,verifier,pollMs:5});return{dir,cwd,pipeline,calls,manager,cleanup:async()=>{await pipeline.shutdown();await rm(dir,{recursive:true,force:true});}};}
async function done(p,id){for(let i=0;i<1000;i++){const s=await p.readStatus(id);if(s.status!=='running')return s;await new Promise(r=>setTimeout(r,5));}throw Error('test timeout');}
test('runs all seven roles and real verifier before completed',async()=>{const f=await fixture();try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});assert.equal((await done(f.pipeline,s.id)).status,'completed');assert.deepEqual(f.calls.map(c=>c.role),Object.keys(output));assert.equal(f.calls.find(c=>c.role==='developer').mode,'workspace-write');assert.equal((await f.pipeline.readResult(s.id)).artifacts.planner.requirements[0].id,'R1');}finally{await f.cleanup();}});
test('failed checks route through developer repair',async()=>{const f=await fixture({checks:n=>({passed:n>1,checks:[{id:'test',status:n>1?'passed':'failed'}],workspaceChanged:false})});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});assert.equal((await done(f.pipeline,s.id)).status,'completed');assert.equal(f.calls.filter(c=>c.role==='developer').length,2);}finally{await f.cleanup();}});
test('no checks never complete',async()=>{const f=await fixture({checks:()=>({passed:true,checks:[],workspaceChanged:false})});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build',maxRepairRounds:0});assert.equal((await done(f.pipeline,s.id)).status,'failed');}finally{await f.cleanup();}});
test('missing acceptance rejects artifact after one formatting retry',async()=>{const f=await fixture({results:{tester:{verdict:'pass',acceptance:[],findings:[]}}});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});assert.equal((await done(f.pipeline,s.id)).status,'failed');assert.equal(f.calls.filter(c=>c.role==='tester').length,2);}finally{await f.cleanup();}});
test('pause cancels active role and resume reruns it',async()=>{const f=await fixture({delay:20});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});await new Promise(r=>setTimeout(r,8));assert.equal((await f.pipeline.pause(s.id)).status,'paused');await f.pipeline.resume({id:s.id});assert.equal((await done(f.pipeline,s.id)).status,'completed');}finally{await f.cleanup();}});
test('workspace claim prohibits overlapping live pipelines and cancel terminal',async()=>{const f=await fixture({delay:50});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});await assert.rejects(f.pipeline.start({cwd:f.cwd,request:'Again'}),/active pipeline/);assert.equal((await f.pipeline.cancel(s.id)).status,'cancelled');await assert.rejects(f.pipeline.resume({id:s.id}),/Terminal/);}finally{await f.cleanup();}});
test('strict contracts reject duplicate and extra fields',()=>{assert.throws(()=>parseRoleResult('planner',JSON.stringify({...output.planner,requirements:[output.planner.requirements[0],output.planner.requirements[0]]})),/unique/);assert.throws(()=>parseRoleResult('developer',JSON.stringify({...output.developer,extra:true})),/unknown/);});
test('another manager observes live owner without interrupting or resuming it',async()=>{const f=await fixture({delay:30});const observer=new PipelineManager({manager:{stateDir:f.dir,ready:Promise.resolve()},pollMs:5});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});assert.equal((await observer.readStatus(s.id)).status,'running');await assert.rejects(observer.resume({id:s.id}),/live owner/);assert.equal((await done(f.pipeline,s.id)).status,'completed');}finally{await observer.shutdown();await f.cleanup();}});
test('strict malformed role artifact never advances to later roles',async()=>{const f=await fixture({results:{architect:{wrong:'output'}}});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});assert.equal((await done(f.pipeline,s.id)).status,'failed');assert.equal(f.calls.some(c=>c.role==='developer'),false);assert.equal(f.calls.filter(c=>c.role==='architect').length,2);}finally{await f.cleanup();}});
test('workspace changes during verification fail honestly after cap',async()=>{const f=await fixture({checks:()=>({passed:true,checks:[{id:'test',status:'passed'}],workspaceChanged:true})});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build',maxRepairRounds:1});const result=await done(f.pipeline,s.id);assert.equal(result.status,'failed');assert.equal(result.round,1);assert.equal(f.calls.filter(c=>c.role==='reviewer').length,2);}finally{await f.cleanup();}});
test('source mutation by reviewer after successful checks prevents completion',async()=>{const f=await fixture();const start=f.manager.start.bind(f.manager);f.manager.start=async input=>{if(input.role==='reviewer')await writeFile(join(f.cwd,'external.txt'),'changed');return start(input);};try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build',maxRepairRounds:0});const result=await done(f.pipeline,s.id);assert.equal(result.status,'failed');assert.equal(result.verification.workspaceChanged,true);}finally{await f.cleanup();}});
test('start failures mark role failed instead of indefinitely running',async()=>{const f=await fixture();f.manager.start=async()=>{throw Error('No authenticated CLI');};try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});const result=await done(f.pipeline,s.id);assert.equal(result.status,'failed');assert.equal(result.roles[0].status,'failed');}finally{await f.cleanup();}});
test('explicit checks reject invalid commands and more than 32 entries at start',async()=>{const f=await fixture();try{await assert.rejects(f.pipeline.start({cwd:f.cwd,request:'Build',checks:[{command:'node',args:'wrong'}]}),/Invalid verification/);await assert.rejects(f.pipeline.start({cwd:f.cwd,request:'Build',checks:Array.from({length:33},(_,i)=>({id:String(i),command:'node',args:[]}))}),/32 entries/);const s=await f.pipeline.start({cwd:f.cwd,request:'Build',maxRepairRounds:20});assert.equal((await done(f.pipeline,s.id)).status,'completed');}finally{await f.cleanup();}});
test('immutable receipts preserve failed checks and changed role artifacts across repair',async()=>{const f=await fixture({checks:n=>({passed:n>1,checks:[{id:'test',status:n>1?'passed':'failed',stdout:'round '+n}],workspaceChanged:false})});try{const s=await f.pipeline.start({cwd:f.cwd,request:'Build'});await done(f.pipeline,s.id);const result=await f.pipeline.readResult(s.id);assert.equal(result.verificationHistory.length,4);assert.equal(result.verificationHistory[0].receipt.passed,false);assert.equal(result.verificationHistory[0].receipt.checks[0].stdout,'round 1');assert.equal(result.verificationHistory[3].receipt.passed,true);assert.equal(result.artifactHistory.filter(a=>a.role==='developer').length,2);assert.notEqual(result.artifactHistory[0].path,result.artifactHistory[1].path);const observer=new PipelineManager({manager:{stateDir:f.dir,ready:Promise.resolve()}});assert.equal((await observer.readResult(s.id)).verificationHistory[0].receipt.passed,false);await observer.shutdown();}finally{await f.cleanup();}});
