import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,mkdir,symlink,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {VerificationRunner,discoverChecks,validateChecks,workspaceFingerprint} from '../verification.mjs';
const node=process.execPath;
async function fixture(t){const d=await mkdtemp(join(tmpdir(),'bongee-check-'));t.after(()=>rm(d,{recursive:true,force:true}));return d;}
const check=code=>({command:node,args:['-e',code]});
test('actual completion and missing executable',async t=>{const cwd=await fixture(t),r=await new VerificationRunner().run({cwd,checks:[check('console.log("ok")'),check('process.exit(7)'),{command:'bongee-no-such-executable',args:[]}]});assert.equal(r.passed,false);assert.deepEqual(r.checks.map(c=>c.status),['passed','failed','failed']);assert.equal(r.checks[1].exitCode,7);assert.equal(r.checks[2].exitCode,null);});
test('timeout kills process',async t=>{const cwd=await fixture(t),r=await new VerificationRunner({timeoutSeconds:.08}).run({cwd,checks:[check('setInterval(()=>{},1000)')]});assert.equal(r.checks[0].status,'timed-out');assert.equal(r.passed,false);});
test('parent abort cancels process tree',async t=>{const cwd=await fixture(t),controller=new AbortController();const pending=new VerificationRunner().run({cwd,checks:[check('require("node:child_process").spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"inherit"});setInterval(()=>{},1000)'),check('console.log("must not run")')],signal:controller.signal});setTimeout(()=>controller.abort(),100);const r=await pending;assert.equal(r.checks[0].status,'cancelled');assert.equal(r.checks.length,1);assert.equal(r.passed,false);});
test('caps output and redacts secrets',async t=>{const cwd=await fixture(t),r=await new VerificationRunner({maxOutput:128}).run({cwd,checks:[check('console.log("Bearer abcsecret api_key=private sk-abcdefghijklmnop");console.log("x".repeat(10000))')]});assert.equal(r.passed,true);assert.equal(r.checks[0].truncated,true);assert.ok(!r.checks[0].stdout.includes('abcsecret'));assert.ok(!r.checks[0].stdout.includes('private'));assert.ok(!r.checks[0].stdout.includes('sk-'));});
test('source mutation invalidates successful tests, build output does not',async t=>{const cwd=await fixture(t);await writeFile(join(cwd,'source.js'),'before');let r=await new VerificationRunner().run({cwd,checks:[check('require("fs").writeFileSync("source.js","after")')]});assert.equal(r.workspaceChanged,true);assert.equal(r.passed,false);r=await new VerificationRunner().run({cwd,checks:[check('require("fs").mkdirSync("dist");require("fs").writeFileSync("dist/a.js","generated")')]});assert.equal(r.passed,true);});
test('no checks cannot pass and explicit empty suppresses discovery',async t=>{const cwd=await fixture(t);assert.equal((await new VerificationRunner().run({cwd})).passed,false);await writeFile(join(cwd,'package.json'),JSON.stringify({scripts:{test:'node --test'}}));assert.equal((await new VerificationRunner().run({cwd,checks:[]})).checks.length,0);});
test('manifest discovery uses bounded ordered nonwatch checks',async t=>{const cwd=await fixture(t);await writeFile(join(cwd,'package.json'),JSON.stringify({scripts:{build:'tsc',typecheck:'tsc --noEmit',check:'tsc --noEmit',lint:'eslint --watch',test:'echo "Error: no test specified" && exit 1'}}));for(const f of ['pyproject.toml','Cargo.toml','go.mod','project.csproj','pom.xml','gradlew','build.gradle'])await writeFile(join(cwd,f),'');assert.deepEqual((await discoverChecks(cwd)).map(c=>c.id),['node-build','node-typecheck','python-test','rust-test','go-test','dotnet-test','maven-test','gradle-test']);});
test('commands never interpolate shell metacharacters',async t=>{const cwd=await fixture(t);const r=await new VerificationRunner().run({cwd,checks:[{command:node,args:['-e','console.log(process.argv[1])','$(touch injected); echo dangerous']}]});assert.equal(r.passed,true);assert.ok(r.checks[0].stdout.includes('$(touch injected)'));assert.throws(()=>validateChecks([{command:'node\nboom',args:[]}]));assert.throws(()=>validateChecks([{command:'node',args:['\0']}]));assert.throws(()=>validateChecks(Array(33).fill(check(''))));});
test('fingerprint deterministic and excludes symlinks outside tree',async t=>{const cwd=await fixture(t);await writeFile(join(cwd,'a'),'one');await mkdir(join(cwd,'nested'));await writeFile(join(cwd,'nested/b'),'two');await symlink('/etc',join(cwd,'outside'));const a=await workspaceFingerprint(cwd);assert.equal(a,await workspaceFingerprint(cwd));await writeFile(join(cwd,'nested/b'),'three');assert.notEqual(a,await workspaceFingerprint(cwd));});
