import {readFileSync} from 'node:fs';
import {validateConnection} from './install-runner.mjs';
const table=Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
export function crc32(data){let c=0xffffffff;for(const byte of data)c=table[(c^byte)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
const command=`#!/bin/zsh -l\nset -eu\ncd -- "$(dirname -- "$0")"\nif ! command -v node >/dev/null 2>&1; then\n  echo 'Node.js 20 이상을 설치한 후 이 연결 파일을 다시 실행하세요.'\n  read -r '?Enter를 누르면 종료합니다.'\n  exit 1\nfi\nnode ./install-runner.mjs ./connection.json\n`;
/** The returned archive contains a private runner credential; never publicly cache it. */
export function createConnectionPackage(config,{releaseTag='v0.3.3'}={}){
 const valid=validateConnection({...config,releaseTag}),entries=[{name:'Bongee-Connect.command',mode:0o100755,data:Buffer.from(command)},{name:'install-runner.mjs',mode:0o100600,data:readFileSync(new URL('./install-runner.mjs',import.meta.url))},{name:'connection.json',mode:0o100600,data:Buffer.from(JSON.stringify(valid,null,2)+'\n')}];let offset=0;const local=[],central=[];
 for(const entry of entries){const name=Buffer.from(entry.name),crc=crc32(entry.data),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(0,8);header.writeUInt16LE(33,12);header.writeUInt32LE(crc,14);header.writeUInt32LE(entry.data.length,18);header.writeUInt32LE(entry.data.length,22);header.writeUInt16LE(name.length,26);local.push(header,name,entry.data);const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50);directory.writeUInt16LE(0x314,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt16LE(33,14);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(entry.data.length,20);directory.writeUInt32LE(entry.data.length,24);directory.writeUInt16LE(name.length,28);directory.writeUInt32LE((entry.mode*65536)>>>0,38);directory.writeUInt32LE(offset,42);central.push(directory,name);offset+=header.length+name.length+entry.data.length;}
 const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directory,end]);
}
