import express from 'express';
import {randomBytes,randomUUID,createHash,timingSafeEqual} from 'node:crypto';
import {mkdir,chmod,open,writeFile,rename,lstat} from 'node:fs/promises';
import {constants} from 'node:fs';
import {dirname} from 'node:path';
const secret=()=>randomBytes(32).toString('base64url');
const hash=value=>createHash('sha256').update(value).digest('hex');
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const escaped=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const loopback=url=>['localhost','127.0.0.1','[::1]'].includes(url.hostname);
function safeUrl(value,{issuer=false}={}){if(typeof value!=='string'||value.length>2048)throw Error('Invalid URL');const url=new URL(value);if(url.username||url.password||url.hash||!(url.protocol==='https:'||(url.protocol==='http:'&&loopback(url)))||(issuer&&(url.search||url.pathname!=='/')))throw Error('HTTPS or loopback HTTP URL required');return url.href;}
const failure=(error,description)=>Object.assign(Error(description),{oauthError:error});
export function createOAuth({publicUrl,statePath,clock=()=>Date.now(),limits={},accessTtlMs=3600000,refreshTtlMs=7*86400000,sessionTtlMs=30*86400000}={}){
 const issuer=safeUrl(publicUrl,{issuer:true}).replace(/\/$/,''),resource=issuer+'/mcp',secure=new URL(issuer).protocol==='https:',cookieName='bongee_oauth_session';
 const caps={clients:1000,sessions:1000,consents:1000,codes:1000,access:5000,refresh:5000,...limits};for(const value of Object.values(caps))if(!Number.isInteger(value)||value<1||value>100000)throw Error('Invalid OAuth limits');for(const ttl of [accessTtlMs,refreshTtlMs,sessionTtlMs])if(!Number.isSafeInteger(ttl)||ttl<1000||ttl>90*86400000)throw Error('Invalid OAuth TTL');
 let db={version:1,clients:{},sessions:{},consents:{},codes:{},access:{},refresh:{}};
 const ready=(async()=>{if(!statePath)return;await mkdir(dirname(statePath),{recursive:true,mode:0o700});try{const file=await open(statePath,constants.O_RDONLY|constants.O_NOFOLLOW);try{const info=await file.stat();if(!info.isFile()||info.size>16*1024*1024)throw Error('Invalid OAuth state file');const loaded=JSON.parse(await file.readFile('utf8'));if(loaded.version!==1||Object.keys(caps).some(k=>!loaded[k]||typeof loaded[k]!=='object'||Array.isArray(loaded[k])||Object.keys(loaded[k]).length>caps[k]))throw Error('Invalid OAuth state');for(const name of Object.keys(caps))for(const value of Object.values(loaded[name])){if(!value||typeof value!=='object'||!Number.isSafeInteger(value.expiresAt))throw Error('Invalid OAuth state entry');if(name!=='clients'&&!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value.principalId))throw Error('Invalid OAuth principal');}db=loaded;await file.chmod(0o600);}finally{await file.close();}}catch(e){if(e.code!=='ENOENT')throw e;}})();
 let tail=Promise.resolve();
 function cleanup(){const now=clock();for(const name of Object.keys(caps))for(const [key,value]of Object.entries(db[name]))if(value.expiresAt<=now)delete db[name][key];}
 async function persist(){if(!statePath)return;try{const info=await lstat(statePath);if(!info.isFile()||info.isSymbolicLink())throw Error('Invalid OAuth state file');}catch(e){if(e.code!=='ENOENT')throw e;}const temp=statePath+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(db),{mode:0o600,flag:'wx'});await rename(temp,statePath);}
 function transaction(fn){const run=tail.catch(()=>{}).then(async()=>{await ready;cleanup();let value;try{value=await fn();}catch(error){await persist();throw error;}await persist();return value;});tail=run;return run;}
 function room(name){if(Object.keys(db[name]).length>=caps[name])throw failure('temporarily_unavailable','OAuth capacity reached');}
 function put(name,key,value){room(name);db[name][key]=value;}
 function cookie(req){const part=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='));if(!part)return null;const value=part.slice(cookieName.length+1);return /^[A-Za-z0-9_-]{43}$/.test(value)?value:null;}
 function browserSession(req,res){const value=cookie(req),existing=value?db.sessions[hash(value)]:null;if(existing&&existing.expiresAt>clock())return {key:hash(value),...existing};const token=secret(),entry={principalId:randomUUID(),expiresAt:clock()+sessionTtlMs};put('sessions',hash(token),entry);res.cookie(cookieName,token,{httpOnly:true,secure,sameSite:'lax',path:'/',maxAge:sessionTtlMs});return {key:hash(token),...entry};}
 function client(id){if(typeof id!=='string'||!Object.hasOwn(db.clients,id))throw failure('invalid_client','Unknown OAuth client');return db.clients[id];}
 function validAuth(params){const c=client(params.client_id);if(params.response_type!=='code')throw failure('unsupported_response_type','Only authorization code supported');if(!c.redirect_uris.includes(params.redirect_uri))throw failure('invalid_request','Redirect must exactly match registration');if(params.code_challenge_method!=='S256'||typeof params.code_challenge!=='string'||! /^[A-Za-z0-9_-]{43}$/.test(params.code_challenge))throw failure('invalid_request','PKCE S256 is required');if(params.scope!==undefined&&params.scope!=='mcp')throw failure('invalid_scope','Only mcp scope supported');if(params.resource!==undefined&&params.resource!==resource)throw failure('invalid_target','Unknown resource');if(params.state!==undefined&&(typeof params.state!=='string'||params.state.length>2048))throw failure('invalid_request','Invalid state');return c;}
 function tokens({clientId,principalId,familyId=randomUUID()}){room('access');room('refresh');const access=secret(),refresh=secret();db.access[hash(access)]={clientId,principalId,familyId,scope:'mcp',expiresAt:clock()+accessTtlMs};db.refresh[hash(refresh)]={clientId,principalId,familyId,used:false,revoked:false,expiresAt:clock()+refreshTtlMs};return {access_token:access,token_type:'Bearer',expires_in:Math.floor(accessTtlMs/1000),refresh_token:refresh,scope:'mcp'};}
 const router=express.Router();router.use(express.json({limit:'64kb'}),express.urlencoded({extended:false,limit:'64kb'}));router.use((req,res,next)=>{res.set('Cache-Control','no-store');res.set('Pragma','no-cache');next();});
 const endpoint=handler=>(req,res,next)=>Promise.resolve(handler(req,res)).catch(error=>{if(res.headersSent)return next(error);res.status(error.oauthError==='temporarily_unavailable'?503:400).json({error:error.oauthError||'server_error',error_description:error.oauthError?error.message:'OAuth operation failed'});});
 const authMetadata={issuer,authorization_response_iss_parameter_supported:true,authorization_endpoint:issuer+'/authorize',token_endpoint:issuer+'/token',registration_endpoint:issuer+'/register',revocation_endpoint:issuer+'/revoke',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],scopes_supported:['mcp']};
 router.get('/.well-known/oauth-authorization-server',(req,res)=>res.json(authMetadata));
 for(const path of ['/.well-known/oauth-protected-resource','/.well-known/oauth-protected-resource/mcp'])router.get(path,(req,res)=>res.json({resource,authorization_servers:[issuer],bearer_methods_supported:['header'],scopes_supported:['mcp'],resource_name:'Bongee MCP'}));
 router.post('/register',endpoint(async(req,res)=>{const result=await transaction(()=>{const body=req.body;if(!body||!Array.isArray(body.redirect_uris)||!body.redirect_uris.length||body.redirect_uris.length>10)throw failure('invalid_client_metadata','Register 1 to 10 redirect URIs');let redirects;try{redirects=body.redirect_uris.map(value=>safeUrl(value));}catch{throw failure('invalid_redirect_uri','Use HTTPS or loopback HTTP redirects');}if(new Set(redirects).size!==redirects.length)throw failure('invalid_client_metadata','Duplicate redirect URI');if(body.token_endpoint_auth_method!==undefined&&body.token_endpoint_auth_method!=='none')throw failure('invalid_client_metadata','Only public clients supported');if(body.grant_types!==undefined&&(!Array.isArray(body.grant_types)||body.grant_types.some(x=>!['authorization_code','refresh_token'].includes(x))))throw failure('invalid_client_metadata','Unsupported grant type');if(body.response_types!==undefined&&(!Array.isArray(body.response_types)||body.response_types.length!==1||body.response_types[0]!=='code'))throw failure('invalid_client_metadata','Only code response supported');if(body.client_name!==undefined&&(typeof body.client_name!=='string'||!body.client_name.trim()||body.client_name.length>128))throw failure('invalid_client_metadata','Invalid client name');const client_id=randomUUID(),entry={client_id,client_name:body.client_name||'MCP client',redirect_uris:redirects,grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',client_id_issued_at:Math.floor(clock()/1000),expiresAt:clock()+90*86400000};put('clients',client_id,entry);const {expiresAt,...metadata}=entry;return metadata;});res.status(201).json(result);}));
 router.get('/authorize',endpoint(async(req,res)=>{const page=await transaction(()=>{const params={...req.query};const c=validAuth(params),session=browserSession(req,res),csrf=secret();put('consents',hash(csrf),{params,sessionKey:session.key,principalId:session.principalId,expiresAt:clock()+5*60000});return {csrf,name:c.client_name};});res.set('Content-Security-Policy',"default-src 'none'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");res.set('X-Frame-Options','DENY');res.type('html').send(`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bongee MCP 연결</title><main><h1>Bongee MCP 연결</h1><p>${escaped(page.name)}에 이 브라우저의 독립된 Bongee 작업 공간 연결을 허용합니다.</p><p>봉이 소유자의 계정이나 PC 실행 권한은 제공되지 않습니다. API 키나 별도 계정을 입력할 필요가 없습니다.</p><form method="post" action="/authorize"><input type="hidden" name="csrf" value="${escaped(page.csrf)}"><button name="decision" value="allow">연결 허용</button><button name="decision" value="deny">취소</button></form></main></html>`);}));
 router.post('/authorize',endpoint(async(req,res)=>{const redirect=await transaction(()=>{if(req.headers.origin&&req.headers.origin!==new URL(issuer).origin)throw failure('invalid_request','Invalid browser origin');const csrf=req.body?.csrf;if(typeof csrf!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(csrf))throw failure('invalid_request','Invalid consent token');const pending=db.consents[hash(csrf)],sessionToken=cookie(req);if(!pending||!sessionToken||!equal(pending.sessionKey,hash(sessionToken))||!db.sessions[pending.sessionKey])throw failure('invalid_request','Consent browser session required');if(!['allow','deny'].includes(req.body.decision))throw failure('invalid_request','Explicit consent required');validAuth(pending.params);const target=new URL(pending.params.redirect_uri);target.searchParams.set('iss',issuer);if(pending.params.state!==undefined)target.searchParams.set('state',pending.params.state);if(req.body.decision==='deny')target.searchParams.set('error','access_denied');else{const code=secret();put('codes',hash(code),{clientId:pending.params.client_id,redirectUri:pending.params.redirect_uri,challenge:pending.params.code_challenge,principalId:pending.principalId,expiresAt:clock()+60000});target.searchParams.set('code',code);}delete db.consents[hash(csrf)];return target.href;});res.redirect(303,redirect);}));
 router.post('/token',endpoint(async(req,res)=>{const result=await transaction(()=>{const body=req.body||{};client(body.client_id);if(body.resource!==undefined&&body.resource!==resource)throw failure('invalid_target','Unknown resource');if(body.grant_type==='authorization_code'){if(typeof body.code!=='string'||typeof body.code_verifier!=='string'||! /^[A-Za-z0-9._~-]{43,128}$/.test(body.code_verifier))throw failure('invalid_grant','Invalid authorization grant');const record=db.codes[hash(body.code)];if(!record||record.clientId!==body.client_id||record.redirectUri!==body.redirect_uri||!equal(record.challenge,createHash('sha256').update(body.code_verifier).digest('base64url')))throw failure('invalid_grant','Authorization grant failed');const result=tokens(record);delete db.codes[hash(body.code)];return result;}if(body.grant_type==='refresh_token'){if(typeof body.refresh_token!=='string')throw failure('invalid_grant','Refresh token required');const record=db.refresh[hash(body.refresh_token)];if(!record||record.clientId!==body.client_id||record.revoked)throw failure('invalid_grant','Refresh grant failed');if(record.used){for(const [key,value]of Object.entries(db.access))if(value.familyId===record.familyId)delete db.access[key];for(const value of Object.values(db.refresh))if(value.familyId===record.familyId)value.revoked=true;throw failure('invalid_grant','Refresh token reuse revoked session');}const result=tokens(record);record.used=true;return result;}throw failure('unsupported_grant_type','Unsupported token grant');});res.json(result);}));
 router.post('/revoke',endpoint(async(req,res)=>{await transaction(()=>{const body=req.body||{};client(body.client_id);if(typeof body.token==='string'){const key=hash(body.token),record=db.access[key]||db.refresh[key];if(record?.clientId===body.client_id){delete db.access[key];if(db.refresh[key])db.refresh[key].revoked=true;}}});res.status(200).end();}));
 router.use((error,req,res,next)=>{if(res.headersSent)return next(error);res.status(400).json({error:'invalid_request',error_description:'Malformed OAuth request'});});
 async function resolveAccessToken(token){await ready;if(typeof token!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(token))return null;const record=db.access[hash(token)];if(!record||record.expiresAt<=clock())return null;return {id:record.principalId,kind:'oauth',clientId:record.clientId,scope:record.scope};}
 async function authenticate(req){const authorization=req.headers?.authorization;if(typeof authorization!=='string'||!/^Bearer [A-Za-z0-9_-]{43}$/i.test(authorization))return null;return resolveAccessToken(authorization.slice(7));}
 async function browserPrincipal(req){await ready;const token=cookie(req),entry=token?db.sessions[hash(token)]:null;return entry&&entry.expiresAt>clock()?entry.principalId:null;}
 async function createBrowserSession(){return transaction(()=>{const token=secret(),principalId=randomUUID();put('sessions',hash(token),{principalId,expiresAt:clock()+sessionTtlMs});return {principalId,cookie:cookieName+'='+token+'; Path=/; HttpOnly; SameSite=Lax; Max-Age='+Math.floor(sessionTtlMs/1000)+(secure?'; Secure':'')};});}
 return {router,ready,issuer,resource,authenticate,resolveAccessToken,browserPrincipal,createBrowserSession,close:()=>tail.catch(()=>{})};
}
