import {AgentManager,ownerIsAlive} from './core.mjs';
import {validateChecks,workspaceFingerprint} from './verification.mjs';
import {ROLE_SCHEMAS,parseRoleResult,validateAcceptance} from './pipeline-contracts.mjs';
import {mkdir,chmod,readFile,writeFile,rename,readdir,unlink,realpath,stat,rmdir} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {randomUUID} from 'node:crypto';
const PHASES=[['planning','기획'],['design','설계·디자인'],['development','개발'],['verification','검증']];
const ROLES={planner:'planning',researcher:'planning',architect:'design',designer:'design',developer:'development',tester:'verification',reviewer:'verification'};
const now=()=>new Date().toISOString();
const overlap=(a,b)=>a===b||a.startsWith(b+sep)||b.startsWith(a+sep);
export class PipelineManager{
 constructor({manager=new AgentManager(),stateDir=join(manager.stateDir,'pipelines'),verifier,pollMs=200}={}){Object.assign(this,{manager,stateDir,verifier,pollMs});this.owned=new Map();this.active=new Map();this.persistQueues=new Map();this.stopping=false;this.ready=this.restore();}
 async restore(){await this.manager.ready;await mkdir(this.stateDir,{recursive:true,mode:0o700});await chmod(this.stateDir,0o700);}
 async atomic(file,value){const temp=file+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(value,null,2),{mode:0o600});await rename(temp,file);}
 async save(s){s.updatedAt=now();s.heartbeatAt=s.updatedAt;const p=(this.persistQueues.get(s.id)||Promise.resolve()).catch(()=>{}).then(()=>this.atomic(join(this.stateDir,s.id,'state.json'),s));this.persistQueues.set(s.id,p);await p;}
 async load(id){if(!/^[\w-]+$/.test(id))throw Error('Invalid pipeline ID');return JSON.parse(await readFile(join(this.stateDir,id,'state.json'),'utf8'));}
 async config(id){return JSON.parse(await readFile(join(this.stateDir,id,'config.json'),'utf8'));}
 async lock(action){const dir=join(this.stateDir,'.claim');for(let i=0;i<100;i++){try{await mkdir(dir,{mode:0o700});await this.atomic(join(dir,'owner.json'),{pid:process.pid});try{return await action();}finally{await unlink(join(dir,'owner.json')).catch(()=>{});await rmdir(dir).catch(()=>{});}}catch(e){if(e.code!=='EEXIST')throw e;let owner;try{owner=JSON.parse(await readFile(join(dir,'owner.json'),'utf8'));}catch{}if(!owner){try{if(Date.now()-(await stat(dir)).mtimeMs>1000)await rmdir(dir);}catch{}}if(owner&&!ownerIsAlive(owner.pid)){await unlink(join(dir,'owner.json')).catch(()=>{});await rmdir(dir).catch(()=>{});}await new Promise(r=>setTimeout(r,20));}}throw Error('Workspace claim busy');}
 async reconcileJobs(s){for(const id of s.activeJobIds||[]){try{const job=await this.manager.readResult(id);if(job.status==='running'||job.status==='queued')throw Error('Prior execution is still alive; wait for supervisor cleanup');}catch(error){if(error.message.includes('still alive'))throw error;if(!error.message.includes('Unknown agent'))throw error;}}}
 async assertClaim(cwd,id){for(const name of await readdir(this.stateDir)){if(name.startsWith('.')||name===id)continue;let s;try{s=await this.load(name);}catch{continue;}if(overlap(cwd,s.cwd)){if((['running','queued'].includes(s.status)||s.executionActive===true)&&ownerIsAlive(s.ownerPid))throw Error('Workspace already has an active pipeline');if(!ownerIsAlive(s.ownerPid))await this.reconcileJobs(s);}}}
 validate(c){if(typeof c.request!=='string'||!c.request.trim()||c.request.length>60000)throw Error('Request must contain 1 to 60000 characters');if(!['codex','claude'].includes(c.provider))throw Error('Invalid provider');for(const [r,p]of Object.entries(c.providers||{}))if(!ROLES[r]||!['codex','claude'].includes(p))throw Error('Invalid role provider');for(const [k,min,max]of [['maxRepairRounds',0,20],['stageTimeoutSeconds',1,600],['checkTimeoutSeconds',1,600]])if(!Number.isInteger(c[k])||c[k]<min||c[k]>max)throw Error('Invalid '+k);if(c.checks!==undefined)c.checks=validateChecks(c.checks);}
 async start(input){await this.ready;const c={provider:'codex',providers:{},maxRepairRounds:3,stageTimeoutSeconds:600,checkTimeoutSeconds:300,...input};this.validate(c);c.cwd=await realpath(resolve(c.cwd));return this.lock(async()=>{await this.assertClaim(c.cwd);const id=randomUUID();await mkdir(join(this.stateDir,id),{mode:0o700});const s={id,cwd:c.cwd,status:'running',ownerPid:process.pid,startedAt:now(),updatedAt:now(),heartbeatAt:now(),currentPhase:'planning',round:0,phases:PHASES.map(([id,label])=>({id,label,status:'pending'})),roles:Object.entries(ROLES).map(([role,phase])=>({role,phase,status:'pending',attempt:0})),activeJobIds:[],executionActive:true,history:[]};await this.atomic(join(this.stateDir,id,'config.json'),c);await this.save(s);this.launch(s,c);return this.summary(s);});}
 summary(s){return {...s};}
 launch(s,c){this.owned.set(s.id,s);const active={abort:new AbortController(),promise:null};this.active.set(s.id,active);active.heartbeat=setInterval(()=>{void this.control(s).then(()=>this.save(s)).catch(()=>active.abort.abort());},1000);active.promise=this.execute(s,c,active).catch(async e=>{if(s.status==='running'){s.status='failed';s.reason=e.message;s.finishedAt=now();await this.save(s);}}).finally(async()=>{clearInterval(active.heartbeat);s.executionActive=false;await this.save(s);this.active.delete(s.id);this.owned.delete(s.id);});}
 async control(s){let disk=await this.load(s.id);try{const command=JSON.parse(await readFile(join(this.stateDir,s.id,'control.json'),'utf8'));if(['paused','cancelled','interrupted'].includes(command.status)){s.status=command.status;s.reason=command.reason;}}catch{}if(['paused','cancelled'].includes(disk.status)&&s.status==='running'){s.status=disk.status;s.reason=disk.reason;}if(this.stopping&&s.status==='running')s.status='interrupted';if(s.status!=='running')throw Error('Pipeline '+s.status);}
 async artifact(id,role){try{return JSON.parse(await readFile(join(this.stateDir,id,role+'.json'),'utf8'));}catch{return undefined;}}
 async prompt(s,c,role){const artifacts={};for(const r of Object.keys(ROLES)){const a=await this.artifact(s.id,r);if(a)artifacts[r]=a;}const payload=JSON.stringify({request:c.request,cwd:c.cwd,role,round:s.round,artifacts,verification:s.verification,repairReasons:s.repairReasons});if(Buffer.byteLength(payload)>90000)throw Error('Handoff context exceeds 90000 bytes; no context was truncated');return 'Execute your assigned role on the actual repository. Read source and project instructions. Do not invent actions, test results, evidence or files. Only developer may edit workspace. Planner must define complete acceptance requirements. Researcher must inspect actual repository. Architect must give implementation and file plan. Designer must give actual UI/UX specification or justify absence of UI. Developer must implement the entire request and repair every reported failure. Tester must cover every planner requirement exactly once, cite concrete evidence, mark unverified honestly. Reviewer independently inspect implementation and evidence; report fail when any requirement is incomplete. Return ONLY JSON satisfying the supplied schema.\n'+payload+'\nJSON schema: '+JSON.stringify(ROLE_SCHEMAS[role]);}
 async role(s,c,role,active){await this.control(s);const r=s.roles.find(r=>r.role===role);r.status='running';s.currentPhase=ROLES[role];s.phases.find(p=>p.id===s.currentPhase).status='running';for(let format=0;format<2;format++){await this.control(s);r.attempt++;await this.save(s);let job;try{job=await this.manager.start({cwd:c.cwd,provider:c.providers?.[role]||c.provider,prompt:await this.prompt(s,c,role)+(format?'\nYour previous response was malformed. Return valid JSON only.':''),mode:role==='developer'?'workspace-write':'read-only',timeoutSeconds:c.stageTimeoutSeconds,resultSchema:ROLE_SCHEMAS[role],pipelineId:s.id,role,name:role,phase:ROLES[role]});}catch(error){r.status='failed';r.error=error.message;s.activeJobIds=[];await this.save(s);throw error;}r.jobId=job.id;s.activeJobIds=[job.id];await this.save(s);let result;while(true){try{await this.control(s);}catch(e){await this.manager.cancel(job.id);throw e;}result=await this.manager.readResult(job.id);if(result.status!=='running'&&result.status!=='queued')break;await new Promise(r=>setTimeout(r,this.pollMs));await this.save(s);}s.activeJobIds=[];if(result.resultTruncated)throw Error(role+' output exceeded artifact limit');if(result.status!=='completed'){r.status='failed';throw Error(role+' execution '+result.status+': '+(result.reason||'provider failure'));}try{const value=parseRoleResult(role,result.finalResult);if(role==='tester')validateAcceptance(value,await this.artifact(s.id,'planner'));await this.atomic(join(this.stateDir,s.id,role+'.json'),value);r.status='completed';s.history.push({at:now(),role,round:s.round,jobId:job.id,status:'completed'});await this.save(s);return value;}catch(e){r.error=e.message;if(format===1){r.status='failed';throw Error(role+' artifact invalid: '+e.message);}}}}
 async checks(s,c,active){await this.control(s);let verifier=this.verifier;if(!verifier){const {VerificationRunner}=await import('./verification.mjs');verifier=new VerificationRunner({timeoutSeconds:c.checkTimeoutSeconds});}const checking=verifier.run({cwd:c.cwd,checks:c.checks,signal:active.abort.signal});const interval=setInterval(()=>{void this.control(s).catch(()=>active.abort.abort());},this.pollMs);try{const result=await checking;await this.control(s);s.verification=result;await this.save(s);return result;}finally{clearInterval(interval);}}
 async execute(s,c,active){for(const role of ['planner','researcher','architect','designer']){if(s.roles.find(r=>r.role===role).status!=='completed')await this.role(s,c,role,active);const phase=ROLES[role];if(s.roles.filter(r=>r.phase===phase).every(r=>r.status==='completed')){s.phases.find(p=>p.id===phase).status='completed';await this.save(s);}}
 while(true){if(s.roles.find(r=>r.role==='developer').status!=='completed')await this.role(s,c,'developer',active);s.phases.find(p=>p.id==='development').status='completed';s.currentPhase='verification';s.phases.find(p=>p.id==='verification').status='running';const evidence=await this.checks(s,c,active);const tester=await this.role(s,c,'tester',active);const reviewer=await this.role(s,c,'reviewer',active);await this.control(s);let finalFingerprint;try{finalFingerprint=await workspaceFingerprint(c.cwd);}catch(error){evidence.reason='Final source fingerprint failed: '+error.message;}evidence.finalFingerprint=finalFingerprint??null;if(!evidence.fingerprintAfter||finalFingerprint!==evidence.fingerprintAfter){evidence.workspaceChanged=true;evidence.passed=false;evidence.reason=evidence.reason||'Source changed after checks during tester/reviewer verification';}await this.save(s);const valid=evidence.passed===true&&Array.isArray(evidence.checks)&&evidence.checks.length>0&&evidence.checks.every(x=>x.status==='passed'||x.status==='pass')&&evidence.workspaceChanged===false&&validateAcceptance(tester,await this.artifact(s.id,'planner'))&&reviewer.verdict==='pass'&&reviewer.findings.length===0;if(valid){s.status='completed';s.finishedAt=now();s.phases.find(p=>p.id==='verification').status='completed';await this.save(s);return;}s.repairReasons={checks:evidence,tester,reviewer};if(s.round>=c.maxRepairRounds)throw Error('Verification failed; repair round limit reached');s.round++;for(const role of ['developer','tester','reviewer'])s.roles.find(r=>r.role===role).status='pending';s.phases.find(p=>p.id==='development').status='pending';await this.save(s);}}
 async readStatus(id){await this.ready;const s=await this.load(id);if(['running','queued'].includes(s.status)&&!ownerIsAlive(s.ownerPid)){s.status='interrupted';s.reason='Owner process is no longer running';}return this.summary(s);}
 async readResult(id){const s=await this.readStatus(id);const artifacts={};for(const r of Object.keys(ROLES)){const a=await this.artifact(id,r);if(a)artifacts[r]=a;}return {...s,artifacts};}
 async list({cwd}={}){await this.ready;const results=[];for(const id of await readdir(this.stateDir)){if(id.startsWith('.'))continue;try{const s=await this.readStatus(id);if(!cwd||s.cwd===resolve(cwd))results.push(s);}catch{}}return results;}
 async stop(id,status){await this.ready;const s=this.owned.get(id)||await this.load(id);if(['completed','cancelled'].includes(s.status))return this.summary(s);s.status=status;s.reason='User requested '+status;await this.atomic(join(this.stateDir,id,'control.json'),{status,reason:s.reason});s.activeJobIds.forEach(jobId=>{void this.manager.cancel(jobId).catch(()=>{});});this.active.get(id)?.abort.abort();await this.save(s);await this.active.get(id)?.promise;return this.readStatus(id);}
 pause(id){return this.stop(id,'paused');}cancel(id){return this.stop(id,'cancelled');}
 async resume({id,...patch}){await this.ready;if(this.active.has(id))throw Error('Pipeline is already owned by this process');return this.lock(async()=>{const s=await this.readStatus(id);if(s.status==='completed'||s.status==='cancelled')throw Error('Terminal pipeline cannot resume');if((s.status==='running'||s.executionActive)&&ownerIsAlive(s.ownerPid))throw Error('Pipeline has live owner');await this.reconcileJobs(s);await this.assertClaim(s.cwd,id);const c={...await this.config(id),...patch};this.validate(c);for(const r of s.roles)if(r.status==='running'||r.status==='failed')r.status='pending';if(s.status==='failed'&&s.currentPhase==='verification'){for(const r of s.roles)if(['developer','tester','reviewer'].includes(r.role))r.status='pending';}await unlink(join(this.stateDir,id,'control.json')).catch(()=>{});s.executionActive=true;s.status='running';delete s.finishedAt;delete s.reason;s.ownerPid=process.pid;s.activeJobIds=[];await this.atomic(join(this.stateDir,id,'config.json'),c);await this.save(s);this.launch(s,c);return this.summary(s);});}
 async shutdown(){await this.ready;this.stopping=true;await Promise.all([...this.owned.keys()].map(id=>this.stop(id,'interrupted')));}
}
